"""empty message

Revision ID: 42e4a060e524
Revises: 
Create Date: 2020-02-27 20:12:14.429879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e4a060e524'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweetText',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweetText', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweetText')
    op.drop_table('topics')
    # ### end Alembic commands ###
