"""empty message

Revision ID: 53257ae7892e
Revises: 
Create Date: 2020-02-09 13:30:25.321552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53257ae7892e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
